version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: bulk-email-postgres
    environment:
      POSTGRES_DB: bulk_email_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bulk-email-network

  # Redis Cache and Queue
  redis:
    image: redis:7-alpine
    container_name: bulk-email-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bulk-email-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: bulk-email-backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/bulk_email_platform
      REDIS_URL: redis://redis:6379
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - bulk-email-network
    command: npm run dev

  # Frontend User Dashboard
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: bulk-email-frontend
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - bulk-email-network
    command: npm run dev

  # Admin Frontend
  admin-frontend:
    build:
      context: ./admin-frontend
      dockerfile: Dockerfile.dev
    container_name: bulk-email-admin
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3002:3002"
    volumes:
      - ./admin-frontend:/app
      - /app/node_modules
    networks:
      - bulk-email-network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  bulk-email-network:
    driver: bridge