# Production ConfigMaps
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: bulk-email-platform
data:
  NODE_ENV: "production"
  PORT: "3000"
  API_VERSION: "v1"
  
  # Database Configuration
  DB_HOST: "postgres-primary-service"
  DB_PORT: "5432"
  DB_NAME: "bulk_email_platform"
  DB_SSL: "true"
  DB_POOL_MIN: "5"
  DB_POOL_MAX: "20"
  
  # Redis Configuration
  REDIS_HOST: "redis-cluster-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  
  # Email Service Configuration
  EMAIL_PROVIDER: "aws-ses"
  AWS_REGION: "us-east-1"
  SES_CONFIGURATION_SET: "bulk-email-platform"
  
  # Rate Limiting
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  
  # Queue Configuration
  QUEUE_CONCURRENCY: "10"
  QUEUE_RETRY_ATTEMPTS: "3"
  QUEUE_RETRY_DELAY: "5000"
  
  # Monitoring
  METRICS_ENABLED: "true"
  LOG_LEVEL: "info"
  
  # Enhanced Security Configuration
  CORS_ORIGIN: "https://perbox.com,https://admin.perbox.com"
  HELMET_ENABLED: "true"
  CSP_ENABLED: "true"
  HSTS_MAX_AGE: "31536000"
  
  # Per-User JWT Configuration
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRES_IN: "15m"
  JWT_REFRESH_EXPIRES_IN: "7d"
  JWT_ISSUER: "perbox-platform"
  JWT_AUDIENCE: "perbox-users"
  
  # Enhanced OTP Configuration
  OTP_LENGTH: "6"
  OTP_EXPIRY_MINUTES: "10"
  OTP_MAX_ATTEMPTS: "3"
  OTP_RATE_LIMIT_WINDOW: "900000"
  OTP_RATE_LIMIT_MAX: "5"
  OTP_CLEANUP_INTERVAL: "300000"
  
  # Pricing Protection Configuration
  PRICING_JWT_EXPIRES_IN: "24h"
  PRICING_VALIDATION_STRICT: "true"
  PRICING_AUDIT_ENABLED: "true"
  
  # Security Monitoring
  ENABLE_THREAT_DETECTION: "true"
  FAILED_LOGIN_THRESHOLD: "5"
  FAILED_LOGIN_WINDOW: "900000"
  SUSPICIOUS_ACTIVITY_THRESHOLD: "10"
  
  # Audit Logging
  AUDIT_LOG_RETENTION_DAYS: "2555"
  ENABLE_AUDIT_LOGGING: "true"
  AUDIT_LOG_LEVEL: "info"
  
  # File Upload with Enhanced Security
  MAX_FILE_SIZE: "10485760"
  ALLOWED_FILE_TYPES: "image/jpeg,image/png,image/webp,video/mp4,video/webm"
  MEDIA_STORAGE_PROVIDER: "s3"
  MEDIA_CDN_ENABLED: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: bulk-email-platform
data:
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://api.perbox.com"
  NEXT_PUBLIC_APP_NAME: "Perbox Platform"
  NEXT_PUBLIC_APP_VERSION: "2.0.0"
  NEXT_PUBLIC_APP_URL: "https://perbox.com"
  
  # CDN Configuration
  NEXT_PUBLIC_CDN_URL: "https://cdn.perbox.com"
  NEXT_PUBLIC_MEDIA_URL: "https://media.perbox.com"
  
  # Enhanced Security Features
  NEXT_PUBLIC_ENABLE_SECURITY_HEADERS: "true"
  NEXT_PUBLIC_CSP_NONCE: ""
  
  # Feature Flags for Home Page Redesign
  NEXT_PUBLIC_ENABLE_PHONE_VERIFICATION: "true"
  NEXT_PUBLIC_ENABLE_EMAIL_SIGNUP: "false"
  NEXT_PUBLIC_ENABLE_GOOGLE_AUTH: "true"
  NEXT_PUBLIC_ENABLE_ANIMATIONS: "true"
  NEXT_PUBLIC_ENABLE_MULTIMEDIA_SHOWCASE: "true"
  NEXT_PUBLIC_ENABLE_PRICING_PROTECTION: "true"
  
  # Performance Configuration
  NEXT_PUBLIC_ENABLE_SW: "true"
  NEXT_PUBLIC_ENABLE_PREFETCH: "true"
  NEXT_PUBLIC_IMAGE_OPTIMIZATION: "true"
  
  # Analytics and Monitoring
  NEXT_PUBLIC_SENTRY_DSN: ""
  NEXT_PUBLIC_GA_TRACKING_ID: ""
  NEXT_PUBLIC_HOTJAR_ID: ""
  NEXT_PUBLIC_MIXPANEL_TOKEN: ""
  
  # Payment Configuration
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ""
  NEXT_PUBLIC_RAZORPAY_KEY_ID: ""

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-frontend-config
  namespace: bulk-email-platform
data:
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://api.bulkemail.com"
  NEXT_PUBLIC_APP_NAME: "Bulk Email Platform Admin"
  NEXT_PUBLIC_APP_VERSION: "1.0.0"
  NEXT_PUBLIC_SENTRY_DSN: ""

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: bulk-email-platform
data:
  redis.conf: |
    # Network
    bind 0.0.0.0
    port 6379
    
    # General
    daemonize no
    supervised no
    pidfile /var/run/redis_6379.pid
    loglevel notice
    logfile ""
    
    # Snapshotting
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir ./
    
    # Replication
    replica-serve-stale-data yes
    replica-read-only yes
    repl-diskless-sync no
    repl-diskless-sync-delay 5
    
    # Security
    requirepass ${REDIS_PASSWORD}
    
    # Memory Management
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    
    # Append Only File
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: bulk-email-platform
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      - "alert_rules.yml"
    
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093
    
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      - job_name: 'backend'
        static_configs:
          - targets: ['backend-service:3000']
        metrics_path: '/metrics'
      
      - job_name: 'postgres'
        static_configs:
          - targets: ['postgres-exporter:9187']
      
      - job_name: 'redis'
        static_configs:
          - targets: ['redis-exporter:9121']
      
      - job_name: 'nginx'
        static_configs:
          - targets: ['nginx-exporter:9113']

  alert_rules.yml: |
    groups:
    - name: bulk-email-platform
      rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High error rate detected
          description: "Error rate is {{ $value }} errors per second"
      
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage
          description: "Memory usage is above 90%"
      
      - alert: DatabaseConnectionFailure
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Database connection failure
          description: "PostgreSQL database is not responding"