# Production Namespace Configuration
apiVersion: v1
kind: Namespace
metadata:
  name: bulk-email-platform
  labels:
    name: bulk-email-platform
    environment: production

---
# Resource Quotas for Production
apiVersion: v1
kind: ResourceQuota
metadata:
  name: production-quota
  namespace: bulk-email-platform
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "50"
    configmaps: "50"

---
# Network Policies for Security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: production-network-policy
  namespace: bulk-email-platform
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          name: monitoring
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector:
        matchLabels:
          name: bulk-email-platform
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80