# Production Secrets Configuration for Enhanced Security Features
# Note: These are templates - actual values should be managed through secure secret management

apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: bulk-email-platform
type: Opaque
data:
  username: # base64 encoded username
  password: # base64 encoded password
  replication-password: # base64 encoded replication password

---
apiVersion: v1
kind: Secret
metadata:
  name: kong-credentials
  namespace: bulk-email-platform
type: Opaque
data:
  password: # base64 encoded kong password

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: bulk-email-platform
type: Opaque
data:
  password: # base64 encoded redis password

---
apiVersion: v1
kind: Secret
metadata:
  name: enhanced-security-secrets
  namespace: bulk-email-platform
type: Opaque
data:
  # Enhanced JWT Security (Note: Per-user secrets are generated dynamically)
  jwt-algorithm: # base64 encoded JWT algorithm (HS256)
  jwt-issuer: # base64 encoded JWT issuer
  jwt-audience: # base64 encoded JWT audience
  
  # Pricing Protection Secrets
  pricing-jwt-secret: # base64 encoded pricing JWT secret
  pricing-validation-key: # base64 encoded pricing validation key
  
  # Enhanced OTP Security
  otp-encryption-key: # base64 encoded OTP encryption key
  otp-signing-secret: # base64 encoded OTP signing secret
  
  # Session and Encryption
  session-secret: # base64 encoded session secret
  encryption-key: # base64 encoded 256-bit encryption key
  webhook-secret: # base64 encoded webhook signing secret

---
apiVersion: v1
kind: Secret
metadata:
  name: phone-verification-credentials
  namespace: bulk-email-platform
type: Opaque
data:
  twilio-account-sid: # base64 encoded Twilio Account SID
  twilio-auth-token: # base64 encoded Twilio Auth Token
  twilio-api-key: # base64 encoded Twilio API Key
  twilio-api-sid: # base64 encoded Twilio API SID
  twilio-service-sid: # base64 encoded Twilio Service SID
  twilio-phone-number: # base64 encoded Twilio Phone Number

---
apiVersion: v1
kind: Secret
metadata:
  name: email-service-credentials
  namespace: bulk-email-platform
type: Opaque
data:
  aws-access-key-id: # base64 encoded AWS access key
  aws-secret-access-key: # base64 encoded AWS secret key
  sendgrid-api-key: # base64 encoded SendGrid API key

---
apiVersion: v1
kind: Secret
metadata:
  name: payment-credentials
  namespace: bulk-email-platform
type: Opaque
data:
  stripe-secret-key: # base64 encoded Stripe secret key
  stripe-webhook-secret: # base64 encoded Stripe webhook secret
  razorpay-key-id: # base64 encoded Razorpay key ID
  razorpay-key-secret: # base64 encoded Razorpay key secret

---
apiVersion: v1
kind: Secret
metadata:
  name: ai-service-credentials
  namespace: bulk-email-platform
type: Opaque
data:
  openai-api-key: # base64 encoded OpenAI API key
  claude-api-key: # base64 encoded Claude API key

---
apiVersion: v1
kind: Secret
metadata:
  name: ssl-certificates
  namespace: bulk-email-platform
type: kubernetes.io/tls
data:
  tls.crt: # base64 encoded SSL certificate
  tls.key: # base64 encoded SSL private key

---
apiVersion: v1
kind: Secret
metadata:
  name: ssl-private-keys
  namespace: bulk-email-platform
type: Opaque
data:
  app.bulkemail.com.key: # base64 encoded private key
  admin.bulkemail.com.key: # base64 encoded private key
  api.bulkemail.com.key: # base64 encoded private key

---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-credentials
  namespace: bulk-email-platform
type: Opaque
data:
  grafana-admin-password: # base64 encoded Grafana admin password
  prometheus-basic-auth: # base64 encoded basic auth for Prometheus